version: "3.8"
services:
    app:
        build:
            context: ./docker/php
        container_name: laravel_app
        volumes:
            - ./:/var/www/html
            - ./docker/php/conf.d:/usr/local/etc/php/conf.d
            - ./storage:/var/www/html/storage
        environment:
            - COMPOSER_ALLOW_SUPERUSER=1
        depends_on:
            - db
        networks:
            - laravel

    nginx:
        image: nginx:1.23-alpine
        container_name: laravel_nginx
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - app
        networks:
            - laravel

    db:
        image: mysql:8.0
        container_name: laravel_db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel_assessment
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        ports:
            - "3307:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel

    redis:
        image: redis:7-alpine
        container_name: laravel_redis
        ports:
            - "6379:6379"
        networks:
            - laravel

volumes:
    dbdata:

networks:
    laravel:
        driver: bridge
